app = "onchain-agent-backend"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONPATH = "/app/src"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 